colonh/urls.py
# -*- encoding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from colonh.settings import STATIC_ROOT, MEDIA_ROOT

from django.conf import settings
from django.conf.urls.static import static



# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

basepatterns = patterns('',
    # Examples:
    # url(r'^$', 'colonh.views.home', name='home'),
    # url(r'^colonh/', include('colonh.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    # editor
    url(r'^ckeditor/', include('ckeditor.urls')),

    
    # registration
    url(r'^accounts/', include('registration.backends.default.urls', namespace='accounts')),

    # apps url    
    # $하면 뒤에 다른거 추가한거랑 다르게 취급됨
    url(r'^about/$', 'Information.views.about'),
    url(r'^editors/$', 'Information.views.editors'),
    url(r'^recruit/$', 'Information.views.recruit'),
    url(r'^contact/$', 'Information.views.contact'),
    
    url(r'^$', 'Volume.views.issue', name='main'),
    url(r'^issue/(\d+)/$', 'Volume.views.issue', name='issue'),
    url(r'^issue/(\d+)/(\w+)', 'Volume.views.issue_item', name='issue_item'),
    url(r'^issues/monthly/$', 'Volume.views.issues_monthly', name='issues_monthly'),
    url(r'^issues/parts/$', 'Volume.views.issues_parts', name='issues_parts'),
    url(r'^issues/parts/(\w+)$', 'Volume.views.issues_parts', name='issues_parts'),

    # news
    url(r'^news/$', 'news.views.news', name='news_all'),
    url(r'^news/(\w+)$', 'news.views.news', name='news'),
    url(r'^news/(\d+)$', 'news.views.news_item', name='news_item'),

    # board
    url(r'^board/qa/$', 'board.views.board_qa', name='board_qa'),
    url(r'^board/qa/(\d+)/$', 'board.views.board_qa_item', name='board_qa_item'),
    url(r'^board/qa/add/$', 'board.views.board_qa_add', name='board_qa_add'),
)
# 로컬이며 DEBUG모드일 경우
if settings.LOCAL and settings.DEBUG:
    print 'Local and DEBUG'
    urlpatterns = patterns('',
        url(r'^/', include(basepatterns)),
    )
    urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT}))
    
# 배포중이며 DEBUG모드일 경우
elif settings.DEBUG:
    print 'Deploy and Debug'
    urlpatterns = patterns('',
        url(r'^colonh/', include(basepatterns)),
    )
    urlpatterns += patterns('',
    (r'^colonh/media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT}))

# 배포중이며 DEBUG가 아닐 경우
else:
    print 'Deploy and NotDebug'
    urlpatterns = patterns('',
        url(r'^colonh/', include(basepatterns)),
    )

registration/backends/simple/urls.py
"""
URLconf for registration and activation, using django-registration's
one-step backend.

If the default behavior of these views is acceptable to you, simply
use a line like this in your root URLconf to set up the default URLs
for registration::

    (r'^accounts/', include('registration.backends.simple.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

If you'd like to customize registration behavior, feel free to set up
your own URL patterns for these views instead.

"""


from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.views.generic.base import TemplateView

from registration.backends.simple.views import RegistrationView


urlpatterns = patterns('',
                       url(r'^register/$',
                           RegistrationView.as_view(),
                           name='registration_register'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       )

news/models.py
from django.db import models
from Volume.models import Part
from ckeditor.fields import RichTextField

# Category
# Title
# Content
# Part
# Created
class Category(models.Model):
    title = models.CharField(max_length=100)
    description = RichTextField()

    def __unicode__(self):
        return self.title


class News(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateField()
    content = RichTextField()
    part = models.ForeignKey(Part)
    category = models.ForeignKey(Category)
    attachment = models.FileField(upload_to='attachment/', blank=True, null=True)

    def __unicode__(self):
        return u"%s, %s" % (self.title, self.created)

news/views.py
from django.shortcuts import render_to_response

from news.models import *
from colonh.settings import MEDIA_URL

def news(request, category=''):
    # d = get_menu_info()
    d = {}

    if category != '':
        try:
            news_list = News.objects.filter(category__title=category.upper())
            d['active'] = category
        except:
            news_list = News.objects.all()
            d['active'] = 'all'
    else:
        news_list = News.objects.all()
        d['active'] = 'all'
        d['media_url'] = MEDIA_URL

    d['news_list'] = news_list

    return render_to_response('v2/news.html', d)

def news_item(request, pk):
    # d = get_menu_info()
    d = {}
    item = News.objects.get(pk=pk)

    d['item'] = item

    return render_to_response('v2/news_item.html', d)

colonh/templates/v2/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Colon H</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet" />
    {% block head %}
    {% endblock %}

</head>

<body>
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function() {
            
            //초기화
            FB.init({
                appId      : '426836870755522', // App ID
                //channelUrl : '//127.0.0.1:8020/rotuebook_html5/WebContent/testCase//FB_channel.html', // Channel File
                status     : true, // check login status
                cookie     : true, // enable cookies to allow the server to access the session
                xfbml      : true  // parse XFBML
            });
            
            //페이지 로드 했을시 호출 
            FB.getLoginStatus(function(response) {
                if (response.status === 'connected') {
                    
                    FB.api('/me', function(user) {
                        if (user) {
                            console.log(user.name);
            
                            var image = document.getElementById('image');
                            image.src = 'http://graph.facebook.com/' + user.id + '/picture';
                            var name = document.getElementById('name');
                            name.innerHTML = user.name
                            var id = document.getElementById('id');
                            id.innerHTML = user.id

                        }
                    }); 
                    var uid = response.authResponse.userID;
                    var accessToken = response.authResponse.accessToken;
                     console.log(accessToken);
                     
                } else if (response.status === 'not_authorized') {
                    // the user is logged in to Facebook, 
                    // but has not authenticated your app
                } else {
                    // the user isn't logged in to Facebook.
                }
            });
            
            //로그인 되는 순간 호출
            FB.Event.subscribe('auth.login', function(response) {
                alert("로그인 되는 순간 호출");
                document.location.reload();
            });
            //로그아웃 되는 순간 호출
            FB.Event.subscribe('auth.logout', function(response) {
                alert("로그아웃 되는 순간 호출");
                document.location.reload();
            });
            
            /*
            FB.login(function(response) {
                if (response.authResponse) {
                    console.log('Welcome!  Fetching your information.... ');
                    FB.api('/me', function(response) {
                        console.log('Good to see you, ' + response.name + '.');
                    });
                } else {
                    console.log('User cancelled login or did not fully authorize.');
                }
            });
            */    
        };
        
        //Feed백에 글남기는 method
        function postToFeed (){
            // calling the API ...
            var obj = {
                method: 'feed',
                link: 'http://hijigoo.cafe24.com/BLOG/FB_finish.html',
                picture: 'http://fbrell.com/f8.jpg',
                name: 'name',
                caption: 'caption',
                description: 'description'
            };
            
            function callback(response) {
                alert("callback Fn");;
            }
            
            FB.ui(obj, callback);
        };
        
        // Load the SDK Asynchronously
        (function(d){
           var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
           if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/ko_KR/all.js";
           ref.parentNode.insertBefore(js, ref);
         }(document));
         //end Load the SDK Asynchronously
         
    </script>
    
    {% if show_menu %}
    <div id="right-menu" class="right-menu">
        <div id="right-menu-toggle" class="right-arrow-zone" style="z-index: 1;">
            <img src="{% static 'img/base/right_menu_open.png' %}" style="width:39px;"/>
        </div>
        <div class="right-issue-menu">
            <div style="font-weight: 900;">ISSUES</div>
            <div class="right-issue-dropdown" style="width:200px;">
                {{ cur_number.title }}
            </div>
            <div id="right-issue-dropdown-toggle">
                <img src="{% static 'img/base/dropdown-close-white.png' %}" style="width:40px;"/>    
            </div>
            
            <div id="right-issue-dropdown-box">
                {% for number in numbers %}
                <div class="right-issue-dropdown-content">
                    {% if number.id == cur_number.id %}
                    <!-- <div style="width: 100%; position: absolute; text-align: left;">
                        <img src="{% static 'img/part/dropdown-open-white.png' %}" style="width:40px; padding-right: 150px; margin-bottom: -20px; margin-top: -20px;"/>
                    </div> -->
                    {% endif %}
                    <a href="{% url 'issue' number.number %}" {% if number.id == cur_number.id %}style=""{% endif %}>
                        {{ number.title }}
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="right-sub-menu"  style="overflow-Y:auto; overflow-X:hidden; height:250px;">
            <div class="right-sub-menu-row1" id="category_title">
                <span style="font-weight: 900; display:inline-block; width: 198px;">CATEGORIES</span>
                <span id="right-sub-menu-dropdown-toggle" style="display:inline-block; width: 40px;">
                    <img src="{% static 'img/base/dropdown-open-black.png' %}" style="width:40px;"/>
                </span>
            </div>
            {% for part in parts %}
            <div class="right-sub-menu-row1">
                <img src="{{ media_url }}{{ part.black_text_image }}"/>
            </div>
            {% for item in cur_items %}
            {% if item.part == part %}
            <div class="right-sub-menu-row2">
                <a href="{% url 'issue_item' item.number.number item.shortTitle %}/">{{ item.title }}</a>
            </div>
            {% endif %}
            {% endfor %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    

    <div id="login">
<!--
        {% if user.is_authenticated %}
            {{ user.last_name }}{{ user.first_name }} 님, 환영합니다 | <a href="{% url 'accounts:auth_logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'accounts:auth_login' %}">Login</a> | <a href="{% url 'accounts:registration_register' %}">Register</a>
        {% endif %}
-->
    </div>

    <div class="container">
        <div class="navbar">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse" style="margin-top: 13px">
                    <!-- 줄임메뉴 아이콘 줄 수 -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="{% url 'main' %}" style="padding-left: 0px; padding-right: 0px; margin-left: 0px"><img src="{% static 'img/base/logo3.png' %}"/></a>

                <!-- 네비게이션 바의 메뉴. 자동으로 메뉴화된다 -->
                <div class="nav-collapse collapse" style="float: right; text-align: right; margin-top:10px;">
                    <ul class="nav">
                        <li class="nav-item {% block about_active %}{% endblock %}"><a href="#">ABOUT</a></li>
                        <li class="nav-item {% block issues_active %}{% endblock %}"><a href="{% url 'issues_monthly' %}">ISSUES</a></li>
                        <li class="nav-item {% block news_active %}{% endblock %}"><a href="{% url 'news_all' %}">NEWS</a></li>
                        <!-- {% url 'news_all' %} -->
                        <li class="nav-item {% block board_active %}{% endblock %}"><a href="{% url 'board_qa' %}">BOARD</a></li>
                        <!-- {% url 'board_qa' %} -->
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div class="container" style="padding-bottom: 20px">
        {% block content %}
        {% endblock %}
    </div>

    <hr/>
    <div style="word-break: break-all; background-color: ;">
        <div class="container" style="padding-top: 15px; padding-bottom:30px; padding-left:10px; padding-right:10px;">
            
            <div class="row-fluid">
                <div class="span6">
                    <div style="font-weight: bold; font-size: 12pt; padding-bottom: 10px;">
                        Contact Us    
                    </div>
                    <div style="font-size: 11pt; padding-left: 10px; padding-bottom:50px;">
                        <a href="https://www.facebook.com/ColonH" target="_blank">Facebook</a> / 
                        <a href="http://blog.naver.com/colon_h" target="_blank">Blog</a> / 
                        <a href="mailto:colon_h@naver.com">E-mail</a>
                    </div>
                    <div style="font-weight: bold; font-size: 12pt; color: black;">
                        Sponsered By<br><br>
                        <img style="padding-left: 10px;" src="{% static 'img/base/glossybox2.jpg' %}"/>
                    </div>        
                </div>
                <div class="span6">
                    <div style="font-size: 11pt; line-height: 20pt; padding-left: 10px;">
                        <br/>
                        COLON H의 모든 컨텐츠 저작권은 COLON H에 있습니다.<br>
                        사전 승인 없이 무단전재 및 재배포를 금지합니다.<br><br>
                        <font color="gray">
                        All rights reserved.<br>
                        All contents may not be published, rewritten or redistribute.<br><br>
                        @2013 Colon H
                        </font>
                    </div>
                    <div class="row-fluid" style="font-size: 9pt; padding-left: 10px; margin-top:30px; text-align:left;">
                        <font color="gray">
                        Site development by Lee HanYeong<br/>
                        Designed by Jang EunKyeong
                        </font>
                    </div>
                    
                </div>
            </div>
            <!-- <div class="row-fluid" style="font-size: 9pt; margin-top:30px; text-align:left;">
                <font color="gray">
                Site development by Lee HanYeong<br/>
                Designed by Jang EunKyeong
                </font>
            </div> -->
        </div>
    </div>

    <script src="{% static 'lib/jquery/jquery-1.9.0.js' %}"></script>
    <script src="{% static 'js/rightmenu.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block bottom_script %}
    {% endblock %}
    {% block after_script %}
    {% endblock %}

</body>

</html>

colonh/templates/v2/board_qa.html
{% extends "v2/base.html" %}


{% block head %}
<style type="text/css">
#news_notice{
    background-color: white;
    height: 40px;
    line-height: 39px;
    font-size: 10pt;
    text-align: center;
    margin-bottom: 17px;
    color: black;

    border-width: 1px;
    border-style: solid;
    border-color: #acacac;
}
#news_category {
    margin-right: 3px;
}
#news_category > .active {
    background-color: black;
    color: white;
    outline-color: black;
}
.category_item {
    display: inline-block;
    width: 50%;
    height: 40px;

    text-align: center;
    font-size: 12px;
    line-height: 40px;


    outline-width: 1px;
    outline-style: solid;
    outline-color: #acacac;
    margin-right: -3px;
    margin-left: 1px;
}
#item_part{
    background-color: black;
    height: 50px;
    line-height: 45px;
    font-size: 15px;

    padding-left: 25px;
    margin-bottom: 20px;
    color: white;

    font-weight: bold;
}

#item_content > p > img {
    width: 100%;
}
.hr {
    width: 100%;
    height: 1px;
    background-color: #acacac;
}
#board {
    margin-top: 81px;
}
#top > #content {
    height: 40px;   
    line-height: 40px;
}
#top > .hr {
    
}
#top > .row > .item {
    text-align: center;
}
.post > .row > .item {
    text-align: center;   
}
.post > .row > .left {
    text-align: left;
}
.post {
    /*width: 100%;*/
    height: 40px;
    line-height: 40px;
}
.post > .hr {

}
.post > .category {
    width: 10%;
    height: 30px;
    line-height: 30px;
    background-color: black;
    color: white;

    text-align: center;
    font-size: 12px;
    float: left;
}
.post > .title {
    margin-top: 20px;

    font-size: 20px;
    font-weight: bold;
}
.post > .content {
    margin-top: 15px;
}
.post > .other {
    margin-top: 10px;
}
.post > .other > .created {
    font-size: 9px;
    margin-right: -20px;    
}
.post > .other > .part {
    font-size: 9px;

}
#bottom {

}
#bottom > .row > .item {
    
}

#scroll_top {
    background-color: black;
    height: 50px;
    line-height: 45px;
    margin-top: 50px;
}

</style>

{% endblock %}

{% block content %}
<div id="news_notice">독자여러분들이 콜론에이치에 대한 의견, 제안, 질문 등을 직접 올릴 수 있는 게시판입니다.</div>
<div id="news_category">
    <span class="category_item">LISTEN TO THE EDITOR</span>
    <span class="category_item active">Q&A</span>
</div>


<div id="board">
    <div id="top">
        <div class="hr"></div>
        <div id="content" class="row">
            <div class="span1 item">#</div>
            <div class="span5 item">SUBJECT</div>
            <div class="span2 item">NAME</div>
            <div class="span2 item">DATE</div>
            <div class="span2 item">COUNT</div>
        </div>
        <div class="hr"></div>
    </div>
    {% for post in posts %}
    <div class="post">
        <div id="content" class="row">
            <div class="span1 item">{{ post.id }}</div>
            <a href="{% url 'board_qa_item' post.id %}">
                <div class="span5 item left">{{ post.title }} [{{ post.comments.count }}]</div>
            </a>
            <div class="span2 item">{{ post.user.last_name }}{{ post.user.first_name }}</div>
            <div class="span2 item">{{ post.created|date:"y/m/d, H:m" }}</div>
            <div class="span2 item"></div>
        </div>
    </div>
    {% endfor %}
    <div id="bottom">
        <div class="hr" style="margin-bottom: 10px;"></div>
        <div class="row">
            <div class="item span1" style="text-align: left;">
                <!-- <div style="margin-left:10px;">List</div> -->
            </div>
            <div class="item span4 offset8" style="text-align: right;">
                {% if user.is_authenticated %}
                    <a href="{% url 'board_qa_add' %}"><div style="margin-right:10px;">Write >></div></a>
                {% else %}
                    글을 쓰려면 로그인 하셔야 합니다
                {% endif %}
            </div>
        </div>
    </div>
</div>




<!-- {% for image in images %}
<img src="{{ media_url }}{{ image.image.name }}" width=100%/><br>
{% endfor %} -->



{% endblock %}


{% block after_script %}
{% endblock %}

colonh/templates/v2/board_qa_add.html
{% extends "v2/base.html" %}
{% load staticfiles %}

{% block head %}
<style type="text/css">
#news_notice{
    background-color: white;
    height: 40px;
    line-height: 39px;
    font-size: 10pt;
    text-align: center;
    margin-bottom: 17px;
    color: black;

    border-width: 1px;
    border-style: solid;
    border-color: #acacac;
}
#news_category {
    margin-right: 3px;
}
#news_category > .active {
    background-color: black;
    color: white;
    outline-color: black;
}
.category_item {
    display: inline-block;
    width: 50%;
    height: 40px;

    text-align: center;
    font-size: 12px;
    line-height: 40px;


    outline-width: 1px;
    outline-style: solid;
    outline-color: #acacac;
    margin-right: -3px;
    margin-left: 1px;
}
#item_part{
    background-color: black;
    height: 50px;
    line-height: 45px;
    font-size: 15px;

    padding-left: 25px;
    margin-bottom: 20px;
    color: white;

    font-weight: bold;
}

#item_content > p > img {
    width: 100%;
}
.hr {
    width: 100%;
    height: 1px;
    background-color: #acacac;
}
#board {
    margin-top: 81px;
}
#top > #content {
    height: 40px;   
    line-height: 40px;
}
#top > .hr {
    
}
#top > .row > .item {
    text-align: center;
}
.post > .row > .item {
    text-align: center;   
}
.post > .row > .left {
    text-align: left;
}
.post {
    /*width: 100%;*/
    height: 40px;
    line-height: 40px;
}
.post > .hr {

}
.post > .category {
    width: 10%;
    height: 30px;
    line-height: 30px;
    background-color: black;
    color: white;

    text-align: center;
    font-size: 12px;
    float: left;
}
.post > .title {
    margin-top: 20px;

    font-size: 20px;
    font-weight: bold;
}
.post > .content {
    margin-top: 15px;
}
.post > .other {
    margin-top: 10px;
}
.post > .other > .created {
    font-size: 9px;
    margin-right: -20px;    
}
.post > .other > .part {
    font-size: 9px;

}
#bottom {

}
#bottom > .row > .item {
    
}

#scroll_top {
    background-color: black;
    height: 50px;
    line-height: 45px;
    margin-top: 50px;
}

</style>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

{% block content %}
<div id="news_notice">독자여러분들이 콜론에이치에 대한 의견, 제안, 질문 등을 직접 올릴 수 있는 게시판입니다.</div>
<div id="news_category">
    <span class="category_item">LISTEN TO THE EDITOR</span>
    <span class="category_item active">Q&A</span>
</div>


<div id="board">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />

    </form>

</div>




<!-- {% for image in images %}
<img src="{{ media_url }}{{ image.image.name }}" width=100%/><br>
{% endfor %} -->



{% endblock %}


{% block after_script %}
{% endblock %}

colonh/templates/v2/issue.html
{% extends "v2/base.html" %}
{% load staticfiles %}
{% load l10n %}

{% block content %}


{% block style %}
<!-- 테두리 -->
<style>
.img_issue_thumbnail2 {
    box-sizing:border-box;
    -moz-box-sizing:border-box;
    -webkit-box-sizing:border-box;
    border-style: solid;
    border-width: 1px;
    border-bottom: 0px;
    border-color: #ACACAC;
}
#issue_description > p{
    font-size: 9pt;
}
</style>
{% endblock %}

<div class="span12" style="margin: 0 auto;">
    <div style="text-align: center; ">
    <img src="
    {% if cur_number.image %}{{ media_url }}{{ cur_number.image }}
    {% else %}{% static 'img/prepare.png' %}
    {% endif %}
    " /><br>
    </div>
    <div class="row-fluid">
        <div class="row-fluid" style="font-size: 11pt; color: white; line-height:40px; background-color: black">
            <div style="font-size: 10pt; font-weight: 900; float:left; background-color: ; text-align:left; margin-left: 16px;">ISSUE {{ cur_number.number }}</div>
            <div style="font-size: 10pt; font-weight: 900; float:right; background-color: ; text-align:right; margin-right: 16px;">{{ cur_number.month }} {{ cur_number.date.year }}</div>
        </div>
    </div>
    <div style="padding-bottom: 100px">
        <div id="issue_description" style="padding-left: 16px; padding-top:10px; padding-bottom:10px; padding-right: 16px; font-size: 12px;">
            {{ cur_number.description|linebreaks }}
        </div>
    </div>

    {% for item in cur_items %}
        {% if forloop.counter0|divisibleby:"2" %}
            <div class="row-fluid">    
        {% endif %}
                <div class="span6"  style="padding-bottom: 50px;">
                    <a href="{% url 'issue_item' cur_number.number item.shortTitle %}"><img src="{{ media_url }}{{ item.thumbnail }}" class="img_issue_thumbnail"/></a><br>
                    <div>
                        <div class="row-fluid" style="font-size: 10pt; color: white; line-height:40px; background-color: black">
                            <div style="float:left; background-color: ; text-align:left; margin-left: 16px;">
                                <img src="{{ media_url }}{{ item.part.white_text_image }}"/>
                            </div>
                            <div style="font-size: 10pt; font-weight: 900; float:right; background-color: ; text-align:right; margin-right:16px;">{{ item.number.month }} {{ item.number.date.year }}</div>
                        </div>
                        <div style="padding-left: 16px; padding-top:10px; padding-bottom:10px; padding-right: 16px;  font-size: 12px;">
                            {{ item.description }}
                        </div>
                    </div>
                </div>
        {% if not forloop.counter0|divisibleby:"2" %}
            </div> 
        {% elif forloop.last %}
            </div>
        {% endif %}

    {% endfor %}
    

</div>

{% endblock %}

colonh/templates/v2/issues_monthly.html
{% extends "v2/base.html" %}
{% load static %}

{% block head %}
<link href="{% static 'css/issues.css' %}" rel="stylesheet">
{% endblock %}

{% block issues_active %}
active
{% endblock %}

{% block content %}
<div class="issues_topbar" style="margin-bottom: 50px;">
    <span class="active">BY MONTH</span>
    <span><a href="{% url 'issues_parts' %}">BY PARTS</a></span>
</div>
{% for number in numbers %}
<div style="">
    <div style="position: relative;">
        <a href="{% url 'issue' number.number %}">
            <div class="issues_monthly_image">
                <img src="
                {% if number.image %}{{ media_url }}{{ number.image }}
                {% else %}{% static 'img/prepare.png' %}
                {% endif %}
                "/><br>
            </div>  

            <div class="issues_monthly_description">
                <table style="width:100%; height: 100%;">
                    <td style="vertical-align:middle; padding:20px; color: white;">
                        <h4>{{ number.title }}</h4>
                        <h6>{{ number.sub_title }}</h6>
                        <div style="height:1px; margin-top:10px; margin-bottom:10px; background-color: white;"></div>
                        {{ number.description }}
                    </td>
                </table>
            </div>
        </a>
    </div>
</div>
<div class="row-fluid"  style="margin-bottom: 100px;">
    <div class="row-fluid issue_cover_bottombar">
        <div class="left" style="margin-left: 16px;">ISSUE {{ number.number }}</div>
        <div class="right" style="margin-right:16px;">{{ number.month }} {{ number.date.year }}</div>
    </div>
</div>

{% endfor %}
{% endblock %}